name: Force check every file for UUID and add it if missing

on:
  workflow_dispatch:

jobs:
  add_uuid:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: run script
        run: |
          python3.12 add_uuid_to_md_missing_one.py

      - name: Check for changes
        id: git-check
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            exit 0;
          else
            exit 1;
          fi 

      - name: Commit and push changes
        if: steps.git-check.outcome == 'success'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Vérifie s'il y a des modifications à commit
          if [[ $(git status --porcelain) ]]; then
            git add .
            git commit -m "Add UUID to new files [skip ci]"  # Message pour éviter le déclenchement en boucle
            git push
          fi

